### ISSUE TITLE
Destructuring nested array returns nil

### ISSUE THREAD

**Issue by nivekuil** [applied-science/js-interop#21]
e.g.
```
(def cljs-foo {:a [1 2 3 4]})
(def js-foo #js {:a [1 2 3 4]})
(j/let [^:js {a :a} js-foo] a) => [1 2 3 4]

(let [{[first second] :a} cljs-foo] first) => 1
(j/let [^:js {[first second] :a} js-foo] first) => nil
```
Great library, btw. I am curious why the ^:js metadata is needed to activate destructuring, as it is a bit cumbersome. Is there a reason to use `j/let` otherwise?

**Comment by mhuebert** [comment]
Thanks for the comment. In your example, js-foo contains a vector rather than an array - as #js is not recursive. That's why the js destructuring doesn't work (We have a j/lit macro that acts like #js but *is* recursive.)

The decision to require a special hint is so that `j/let` behaves exactly like `let` except for forms that are intentionally tagged. This makes it possible to add/remove to an existing code base without breaking anything. our version of let could be used everywhere in any clojure code and it would still work.

**Comment by nivekuil** [comment]
Ahh, I totally missed that!  Thanks for pointing it out.  I think I'll be reaching for j/lit in the future over #js just as a safety measure.
