### ISSUE TITLE
j/get-in macro v.s j/get-in function

### ISSUE THREAD

**Issue by lucywang000** [applied-science/js-interop#24]
Hey, thanks for making this awesome library. I'm trying to understand how it works under the hood.

Take `j/get-in` as an example. There is a macro version https://github.com/applied-science/js-interop/blob/2e8576b47616f168ee8c065a948e5990b93f7f5b/src/main/applied_science/js_interop.clj#L129

and a cljs function version: https://github.com/applied-science/js-interop/blob/2e8576b47616f168ee8c065a948e5990b93f7f5b/src/main/applied_science/js_interop.cljs#L42

The thing that puzzles me is: to me the cljs function version looks not necessary, because when I call `(j/get-in foo [:bar :baz])` in my application code, it would macro-expand to a series of calls to `cljs.core/unchecked-get` at compile time. 

Am I missing something?

**Comment by mhuebert** [comment]
Hi @lucywang000, thanks for writing. The nuances of macros in ClojureScript took me a long time to grok. The short answer is that a macro can only be placed in the first position of an s-expression, eg. `(+ 1 2)`. A macro needs to be in this position so that it can 'see' the arguments being passed to it (in this case, 1 and 2), as it is a kind of code-rewriting rule. Functions are more versatile - you can see them 'floating around' as values, such that they have no 'literal' visibility of the arguments they will  passed - eg. in `(reduce + 0 [1 2 3])`, the `+` can have no awareness that it will be used to sum up the numbers 1, 2 and 3 - that happens only at evaluation-time. Other examples would include partial application `(partial + 10)`, usage with map/filter `(map + [1 2 3])`, composition `(comp pos? (partial + 10))`. 

In ClojureScript we have the ability to bind the same name to both a macro (for situations where it appears in the first position of an expression) and a function (for all other uses). In my experience this is usually for performance reasons; the macro will do a bit of extra work at compile-time, so that less needs to happen at runtime, or can directly emit some efficient javascript. `+` is an example of something in the standard library that uses this approach.
